spring.application.name=api

# # # #Porta do servido
# server.port = 8080
# # # #Caminho do banco de dados ##LOCALHOST
# spring.datasource.url = jdbc:postgresql://localhost:5432/db_postgreSQL

#--------------------------------------------------------------------------------
# spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/db_postgreSQL
#--------------------------------------------------------------------------------

# Nome do usuario de conexao do banco de dados
# spring.datasource.username = postgres
# # # # #senha do banco de dados
# spring.datasource.password = admin
# # # # #nome do drive
# spring.datasource.driver-class-name = org.postgresql.Driver


# # # Configuracao para indertificar o hibernete para gerar atualizações automaticas constantemente no schema.
# spring.jpa.hibernate.ddl-auto = update
# spring.jpa.show-sql=true

# # Configurações do email (Mailtrap)
# spring.mail.host=smtp.mailtrap.io
# spring.mail.port=2525
# spring.mail.username=331d8e06a48ca1
# spring.mail.password=485e41f7a8f9ec
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# # Configurações do RabbitMQ
# Para rodar o Spring dentro do Docker, use o nome do serviço do RabbitMQ definido no docker-compose.yml
# spring.rabbitmq.host=rabbitmq
#--------------------------------------------------------
# Endereço (use localhost se o Spring rodar fora do Docker)
# spring.rabbitmq.host=localhost
#--------------------------------------------------------
# spring.rabbitmq.port=5672
# spring.rabbitmq.username=guest
# spring.rabbitmq.password=guest


#-----------------------------------------------------------------------#

# Configurações do Deployment Railway

    # Configurações do RabbitMQ

# Configurações do banco de dados Deploy
# Banco de dados Railway
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Porta Railway
server.port=${PORT:8080}

# Configurações do Mailtrap (Spring Mail)

# Configuração da API HTTP do Mailtrap
spring.mail.host=${EMAIL_HOST:live.smtp.mailtrap.io}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# Configuração do RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USER:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSW:guest}